name: clubartisticaserradells
favicon: null
layout_spectrum: 0.8222157501149923
typography_spectrum: 0.4431191848125309
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5938802207820117
  lightness: 0.6353318283800036
  saturation: 0.1668864106759429
  rhythmicContrast: 0.11813248065300286
purpose: []
